In [1]:
import numpy as np
import math

# Alpha

alpha_degree1=-90
alpha_degree2=0
alpha_degree3=0
alpha_degree4=-90
alpha_degree5=0
alpha1=np.deg2rad(alpha_degree1)
alpha2=np.deg2rad(alpha_degree2)
alpha3=np.deg2rad(alpha_degree3)
alpha4=np.deg2rad(alpha_degree4)
alpha5=np.deg2rad(alpha_degree5)

# Theta

theta_degree1=93
theta_degree2=-18.3
theta_degree3=-149.9
theta_degree4=-9.2
theta_degree5=16.2
theta1=np.deg2rad(theta_degree1)
theta2=(np.deg2rad(theta_degree2)-1.38)
theta3=(np.deg2rad(theta_degree3)+2.73)
theta4=(np.deg2rad(theta_degree4)-1.35)
theta5=np.deg2rad(theta_degree5)

#

a1=0
a2=289.48866
a3=351.158796
a4=76
a5=0

# Length of link

d1=267
d2=0
d3=0
d4=0
d5=97

#joint 1

DHT1=np.matrix([[np.cos(theta1),-np.cos(alpha1)*np.sin(theta1), np.sin(alpha1)*np.sin(theta1), a1*np.cos(theta1)],
              [np.sin(theta1), np.cos(alpha1)*np.cos(theta1),-np.sin(alpha1)*np.cos(theta1),a1*np.sin(theta1)],
              [0,np.sin(alpha1),np.cos(alpha1),d1],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT1 is \n',DHT1)

#joint 2

DHT2=np.matrix([[np.cos(theta2),-np.cos(alpha2)*np.sin(theta2), np.sin(alpha2)*np.sin(theta2), a2*np.cos(theta2)],
              [np.sin(theta2), np.cos(alpha2)*np.cos(theta2),-np.sin(alpha2)*np.cos(theta2),a2*np.sin(theta2)],
              [0,np.sin(alpha2),np.cos(alpha2),d2],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT2 is \n', DHT2)

#joint 3

DHT3=np.matrix([[np.cos(theta3),-np.cos(alpha3)*np.sin(theta3), np.sin(alpha3)*np.sin(theta3), a3*np.cos(theta3)],
              [np.sin(theta3), np.cos(alpha3)*np.cos(theta3),-np.sin(alpha3)*np.cos(theta3),a3*np.sin(theta3)],
              [0,np.sin(alpha3),np.cos(alpha3),d3],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT3 is \n',DHT3)

#joint 4

DHT4=np.matrix([[np.cos(theta4),-np.cos(alpha4)*np.sin(theta4), np.sin(alpha4)*np.sin(theta4), a4*np.cos(theta4)],
              [np.sin(theta4), np.cos(alpha4)*np.cos(theta4),-np.sin(alpha4)*np.cos(theta4),a4*np.sin(theta4)],
              [0,np.sin(alpha4),np.cos(alpha4),d4],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT4 is \n',DHT4)

#joint 5

DHT5=np.matrix([[np.cos(theta5),-np.cos(alpha5)*np.sin(theta5), np.sin(alpha5)*np.sin(theta5), a5*np.cos(theta5)],
              [np.sin(theta5), np.cos(alpha5)*np.cos(theta5),-np.sin(alpha5)*np.cos(theta5),a5*np.sin(theta5)],
              [0,np.sin(alpha5),np.cos(alpha5),d5],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT5 is \n',DHT5)

# Post Multiplication of 5 joints
A=np.dot(DHT1,DHT2)
B=np.dot(A,DHT3)
C=np.dot(B,DHT4)
TotalEffect=np.dot(C,DHT5)

print('Postion of the arm is \n',TotalEffect)
#p=[[0],[0],[0],[1]]
#pm=np.dot(TotalEffect_2,p)
#pm


# get the desired row value

X = TotalEffect[0, 3]
print('Postion of the arm in X axis is : ', X )
Y = TotalEffect[1, 3]
print('Postion of the arm in Y axis is : ', Y )
Z = TotalEffect[2, 3]
print('Postion of the arm in Z axis is : ', Z )


DHT1 is 
 [[-0.1 -0.0 -1.0 -0.0]
 [ 1.0 -0.0 -0.1  0.0]
 [ 0.0 -1.0  0.0  267.0]
 [ 0.0  0.0  0.0  1.0]]
DHT2 is 
 [[-0.1  1.0 -0.0 -37.1]
 [-1.0 -0.1  0.0 -287.1]
 [ 0.0  0.0  1.0  0.0]
 [ 0.0  0.0  0.0  1.0]]
DHT3 is 
 [[ 1.0 -0.1  0.0  348.9]
 [ 0.1  1.0 -0.0  39.9]
 [ 0.0  0.0  1.0  0.0]
 [ 0.0  0.0  0.0  1.0]]
DHT4 is 
 [[ 0.1  0.0  1.0  4.6]
 [-1.0  0.0  0.1 -75.9]
 [ 0.0 -1.0  0.0  0.0]
 [ 0.0  0.0  0.0  1.0]]
DHT5 is 
 [[ 1.0 -0.3  0.0  0.0]
 [ 0.3  1.0 -0.0  0.0]
 [ 0.0  0.0  1.0  97.0]
 [ 0.0  0.0  0.0  1.0]]
Postion of the arm is 
 [[ 0.3  0.9 -0.0  6.0]
 [-0.9  0.3  0.0 -113.7]
 [ 0.0 -0.0  1.0  1005.6]
 [ 0.0  0.0  0.0  1.0]]
Postion of the arm in X axis is :  5.959002772678978
Postion of the arm in Y axis is :  -113.70454642803821
Postion of the arm in Z axis is :  1005.5660441538184


In [2]:
import numpy as np
import math

# Alpha

alpha_degree1= float(input("Enter the Alpha Angle of First Joint :"))
alpha_degree2= float(input("Enter the Alpha Angle of Second Joint :"))
alpha_degree3= float(input("Enter the Alpha Angle of Third Joint :"))
alpha_degree4= float(input("Enter the Alpha Angle of Fourth Joint :"))
alpha_degree5= float(input("Enter the Alpha Angle of Fifth Joint :"))
alpha1=np.deg2rad(alpha_degree1)
alpha2=np.deg2rad(alpha_degree2)
alpha3=np.deg2rad(alpha_degree3)
alpha4=np.deg2rad(alpha_degree4)
alpha5=np.deg2rad(alpha_degree5)

# Theta

theta_degree1= float(input("Enter the Theta Angle of First Joint :"))
theta_degree2= float(input("Enter the Theta Angle of Second Joint :"))
theta_degree3= float(input("Enter the Theta Angle of Third Joint :"))
theta_degree4= float(input("Enter the Theta Angle of Fourth Joint :"))
theta_degree5= float(input("Enter the Theta Angle of Fifth Joint :"))
theta1=np.deg2rad(theta_degree1)
theta2=(np.deg2rad(theta_degree2)-1.38)
theta3=(np.deg2rad(theta_degree3)+2.73)
theta4=(np.deg2rad(theta_degree4)-1.35)
theta5=np.deg2rad(theta_degree5)

#

a1= float(input("Enter the Link Length of First Joint a1 :"))
a2= float(input("Enter the Link Length of Second Joint a2 :"))
a3= float(input("Enter the Link Length of Third Joint a3 :"))
a4= float(input("Enter the Link Length of Fourth Joint a4 :"))
a5= float(input("Enter the Link Length of Fifth Joint a5 :"))

# Length of link

d1= float(input("Enter the Joint Distance of First Joint d1 :"))
d2= float(input("Enter the Joint Distance of Second Joint d2 :"))
d3= float(input("Enter the Joint Distance of Third Joint d3 :"))
d4= float(input("Enter the Joint Distance of Fourth Joint d4 :"))
d5= float(input("Enter the Joint Distance of Fifth Joint d5 :"))

#joint 1

DHT1=np.matrix([[np.cos(theta1),-np.cos(alpha1)*np.sin(theta1), np.sin(alpha1)*np.sin(theta1), a1*np.cos(theta1)],
              [np.sin(theta1), np.cos(alpha1)*np.cos(theta1),-np.sin(alpha1)*np.cos(theta1),a1*np.sin(theta1)],
              [0,np.sin(alpha1),np.cos(alpha1),d1],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT1 is \n',DHT1)

#joint 2

DHT2=np.matrix([[np.cos(theta2),-np.cos(alpha2)*np.sin(theta2), np.sin(alpha2)*np.sin(theta2), a2*np.cos(theta2)],
              [np.sin(theta2), np.cos(alpha2)*np.cos(theta2),-np.sin(alpha2)*np.cos(theta2),a2*np.sin(theta2)],
              [0,np.sin(alpha2),np.cos(alpha2),d2],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT2 is \n', DHT2)

#joint 3

DHT3=np.matrix([[np.cos(theta3),-np.cos(alpha3)*np.sin(theta3), np.sin(alpha3)*np.sin(theta3), a3*np.cos(theta3)],
              [np.sin(theta3), np.cos(alpha3)*np.cos(theta3),-np.sin(alpha3)*np.cos(theta3),a3*np.sin(theta3)],
              [0,np.sin(alpha3),np.cos(alpha3),d3],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT3 is \n',DHT3)

#joint 4

DHT4=np.matrix([[np.cos(theta4),-np.cos(alpha4)*np.sin(theta4), np.sin(alpha4)*np.sin(theta4), a4*np.cos(theta4)],
              [np.sin(theta4), np.cos(alpha4)*np.cos(theta4),-np.sin(alpha4)*np.cos(theta4),a4*np.sin(theta4)],
              [0,np.sin(alpha4),np.cos(alpha4),d4],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT4 is \n',DHT4)

#joint 5

DHT5=np.matrix([[np.cos(theta5),-np.cos(alpha5)*np.sin(theta5), np.sin(alpha5)*np.sin(theta5), a5*np.cos(theta5)],
              [np.sin(theta5), np.cos(alpha5)*np.cos(theta5),-np.sin(alpha5)*np.cos(theta5),a5*np.sin(theta5)],
              [0,np.sin(alpha5),np.cos(alpha5),d5],
              [0,0,0,1]])
np.set_printoptions(formatter={'float': '{: 0.1f}'.format})
print('DHT5 is \n',DHT5)

# Post Multiplication of 5 joints
A=np.dot(DHT1,DHT2)
B=np.dot(A,DHT3)
C=np.dot(B,DHT4)
TotalEffect=np.dot(C,DHT5)

print('Postion of the arm is \n',TotalEffect)
#p=[[0],[0],[0],[1]]
#pm=np.dot(TotalEffect_2,p)
#pm


# get the desired row value

X = TotalEffect[0, 3]
print('Postion of the arm in X axis is : ', X )
Y = TotalEffect[1, 3]
print('Postion of the arm in Y axis is : ', Y )
Z = TotalEffect[2, 3]
print('Postion of the arm in Z axis is : ', Z )


DHT1 is 
 [[ 0.7 -0.6  0.4  7.1]
 [ 0.7  0.6 -0.4  7.1]
 [ 0.0  0.5  0.9  10.0]
 [ 0.0  0.0  0.0  1.0]]
DHT2 is 
 [[ 0.4  0.9 -0.2  2.7]
 [-0.9  0.4 -0.1 -6.4]
 [ 0.0  0.3  1.0  12.0]
 [ 0.0  0.0  0.0  1.0]]
DHT3 is 
 [[-1.0 -0.0  0.0 -6.0]
 [ 0.0 -0.9  0.3  0.2]
 [ 0.0  0.3  0.9  12.0]
 [ 0.0  0.0  0.0  1.0]]
DHT4 is 
 [[ 0.6  0.8 -0.3  2.8]
 [-0.8  0.5 -0.2 -4.2]
 [ 0.0  0.3  0.9  12.0]
 [ 0.0  0.0  0.0  1.0]]
DHT5 is 
 [[ 0.7 -0.7  0.1  3.5]
 [ 0.7  0.7 -0.1  3.5]
 [ 0.0  0.2  1.0  12.0]
 [ 0.0  0.0  0.0  1.0]]
Postion of the arm is 
 [[-0.6 -0.3  0.8  24.4]
 [ 0.4 -0.9  0.0 -2.9]
 [ 0.7  0.3  0.7  53.6]
 [ 0.0  0.0  0.0  1.0]]
Postion of the arm in X axis is :  24.411685489481766
Postion of the arm in Y axis is :  -2.8704873824446007
Postion of the arm in Z axis is :  53.59139363470511
